[package]
name = "proof"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest  = { version =  "0.12.23", features = [] }
serde  = { version =  "1.0.228", features = ["derive"] }
tokio  = { version =  "1.47.1", features = ["full"] }
