[setup]
base_url = "http://localhost:6969"
command = "cargo"
args = ["r", "-p", "test_app"]
ready_when = "/health"
database_url_env = "DATABASE_URL"

[db]
db_type = "postgres"
migration_dir = "./utils/test_app/migrations"

[before_each]
reset = true
run_sql = [
  "INSERT INTO USER (id, name) VALUES (1, 'Harry Potter');",
  "INSERT INTO USER (id, name) VALUES (2, 'Hermione Granger');"
]

# Group 1: auth tests
[[test_groups]]
name = "auth"

[test_groups.before_each]
reset = false
run_sql = [
  "DELETE FROM SESSION;"
]

  [[test_groups.tests]]
  name = "LoginUser"
  method = "POST"
  url = "/login"
  body = { username = "alice", password = "1234" }
  assert_status = 200
  assert_header = {Content-Type = "application/json"}

  [[test_groups.tests]]
  name = "LogoutUser"
  method = "POST"
  url = "/logout"
  assert_status = 200

# Group 2: user tests
[[test_groups]]
name = "users"

[test_groups.before_each]
reset = true
run_sql = [
  "DELETE FROM USER;"
]

  [[test_groups.tests]]
  name = "GetUser"
  method = "GET"
  url = "/users/1"
  assert_status = 200

  [[test_groups.tests]]
  name = "CreateUser"
  method = "POST"
  url = "/users"
  body = { name = "Bob" }
  assert_status = 201
