[setup]
mode = "external"
base_url = "http://localhost:6969"

[[tests]]
name = "CreateUser"
method = "POST"
url = "/users/22"
body = { name = "Alice" }

[assert]
status = 200
headers = { "Content-Type" = "application/json" }
jsonpath = { "$.name" = "Alice" }

[[tests]]
name = "HealthCheck"
method = "GET"
url = "/health"

assert_status = 200

[[tests]]
name = "ListUsers"
method = "GET"
url = "/users"

assert_status = 200
assert_jsonpath = { "$.users[0].name" = "Alice" }
