[setup.server]
mode = "external"
url = "http://localhost:3000"

[[tests]]
name = "health check"
method = "GET"
url = "/health"
expect_status = 200

[[tests]]
name = "create user"
method = "POST"
url = "/users"
body = { name = "Alice" }
expect_status = 200
expect_jsonpath = { "$.name" = "Alice" }

[[tests]]
name = "list users"
method = "GET"
url = "/users"
expect_status = 200
expect_jsonpath = { "$.users[0].name" = "Alice" }
