[setup]
mode = "external"
base_url = "http://localhost:6969"

[[tests]]
name = "create user"
method = "POST"
url = "/users/22"
body = { name = "Alice" }
assert_status = 200
assert_headers = { "Content-Type" = "Application/json" }
assert_jsonpath = { "$.name" = "Alice" }

[[tests]]
name = "health check"
method = "GET"
url = "/health"
assert_status = 200

[[tests]]
name = "list users"
method = "GET"
url = "/users"
assert_status = 200
assert_jsonpath = { "$.users[0].name" = "Alice" }
