[setup]
base_url = "http://localhost:6969"
command = "cargo"
args = ["r", "-p", "test_app"]
ready_when = "/health"
database_url_env = "DATABASE_URL"

[db]
db_type = "postgres"
migration_dir = "./utils/test_app/migrations"

[[tests]]
name = "GetUser"
method = "GET"
url = "/users/1"
body = { name = "Alice" }
assert_status = 200
assert_headers = { "Content-Type" = "application/json" }

[[tests]]
name = "HealthCheck"
method = "GET"
url = "/health"
assert_status = 200

[[tests]]
name = "ListUsers"
method = "GET"
url = "/users"
assert_status = 200

[[tests]]
name = "CreateUser"
method = "POST"
url = "/users"
assert_status = 201
