[setup]
mode = "external"
base_url = "http://localhost:6969"
command = "cargo r -p test_app"
ready_when = ""

[db]
db_type = "postgres"
migrations = "./migrations"
runtime = "docker"

[[tests]]
name = "CreateUser"
method = "GET"
url = "/users/1"
body = { name = "Alice" }

[assert]
status = 200
headers = { "Content-Type" = "application/json" }

[[tests]]
name = "HealthCheck"
method = "GET"
url = "/health"
assert_status = 200

[[tests]]
name = "ListUsers"
method = "GET"
url = "/users"
assert_status = 400
