[setup]
base_url = "http://localhost:6969"
command = "cargo"
args = ["r", "-p", "test_app"]
ready_when = "/health"
env = { SOME_ENV = "some_env_value" }

[db]
db_type = "postgres"
image_ref = { name = "postgis/postgis", tag = "15-3.5-alpine" }
migration_dir = "./utils/test_app/migrations"

[global]
headers = { Authorization = "api-key 1234-1234-1234-1234" }

# --------------------
# Group 1: Auth tests
# --------------------
[[test_groups]]
name = "auth"

[test_groups.before_group]
reset = true
run_sql = ["""INSERT INTO users (id, name, password) VALUES
    (1, 'Alice', '123'),
    (2, 'Harry Potter', '1234'),
    (3, 'Charlie', '4321')
ON CONFLICT (id) DO NOTHING;"""]

[[test_groups.tests]]
name = "LoginUser"
method = "POST"
url = "/login"
query = "?hello=world&world=hello"
headers = { Authorization = "api-key 234-1234-1234-1234" }
body = { username = "Harry Potter", password = "1234" }
assert_status = 200
assert_headers = { Content-Type = "application/json" }

[[test_groups.tests]]
before_run = { run_sql = [
  "INSERT INTO users (id, name, password) VALUES (6, 'Harry Plotter', '123') ON CONFLICT (id) DO NOTHING;",
] }
name = "ChangeUserPasswordFail"
method = "PATCH"
url = "/login/password/change"
body = { username = "Harry Potter", password = "123123" }
assert_status = 200
assert_headers = { Content-Length = "0" }
assert_sql = { query = "SELECT * FROM users WHERE name = 'Harry Potter';", expect = "1223" }

[[test_groups.tests]]
name = "LogoutUser"
method = "POST"
url = "/logout"
assert_status = 404

# --------------------
# Group 2: User tests
# --------------------
[[test_groups]]
name = "users"

[test_groups.before_group]
reset = true
run_sql = ["""INSERT INTO users (id, name, password) VALUES
    (1, 'Alice', '123'),
    (2, 'Harry Potter', '1234'),
    (3, 'Charlie', '4321')
ON CONFLICT (id) DO NOTHING;"""]

[[test_groups.tests]]
name = "DeleteUser"
method = "DELETE"
url = "/users/1"
assert_status = 200
assert_json = { id = 1, name = "Alice", password = "23" }

[[test_groups.tests]]
before_run = { reset_db = true, run_sql = [
  "INSERT INTO users (id, name, password) VALUES (1, 'Alice', '123') ON CONFLICT (id) DO NOTHING;",
  "INSERT INTO users (id, name, password) VALUES (2, 'Alice', '123') ON CONFLICT (id) DO NOTHING;",
  "INSERT INTO users (id, name, password) VALUES (6, 'Harry Plotter', '123') ON CONFLICT (id) DO NOTHING;",
] }
name = "GetUser"
method = "GET"
url = "/users/1"
assert_status = 200

[[test_groups.tests]]
before_run = { run_sql = [
  "DELETE FROM users;",
  "INSERT INTO users (id, name, password) VALUES (10, 'Alice', '123') ON CONFLICT (id) DO NOTHING;",
] }
name = "CreateUser"
method = "POST"
url = "/users"
body = { name = "Bob" }
assert_status = 201
assert_sql = { query = "SELECT name || ' - ' || id FROM users;", expect = "Alice - 10, new_name - 11" }
